#ifndef BeerXml_XmlTags_h
#define BeerXml_XmlTags_h

// MAIN TAGS
#define BXTagRecipes @"RECIPES"
#define BXTagRecipe @"RECIPE"
#define BXTagHops @"HOPS"
#define BXTagHop @"HOP"
#define BXTagStyle @"STYLE"

// RECIPE
#define BXTagRecipeVersion @"VERSION"
#define BXTagRecipeName @"NAME"
#define BXTagRecipeType @"TYPE"
#define BXTagRecipeBrewer @"BREWER"
#define BXTagRecipeAssistantBrewer @"ASST_BREWER"
#define BXTagRecipeBatchSize @"BATCH_SIZE"
#define BXTagRecipeBoilSize @"BOIL_SIZE"
#define BXTagRecipeBoilTime @"BOIL_TIME"
#define BXTagRecipeEfficiency @"EFFICIENCY"
#define BXTagRecipeFermentables @"FERMENTABLES"
#define BXTagRecipeMiscs @"MISCS"
#define BXTagRecipeYeasts @"YEASTS"
#define BXTagRecipeWaters @"WATERS"
#define BXTagRecipeMash @"MASH"
#define BXTagRecipeNotes @"NOTES"
#define BXTagRecipeTasteNotes @"TASTE_NOTES"
#define BXTagRecipeTasteRating @"TASTE_RATING"
#define BXTagRecipeOriginalGravity @"OG"
#define BXTagRecipeFinalGravity @"FG"
#define BXTagRecipeFermentationStages @"FERMENTATION_STAGES"
#define BXTagRecipePrimaryAge @"PRIMARY_AGE"
#define BXTagRecipePrimaryTemperature @"PRIMARY_TEMP"
#define BXTagRecipeSecondaryAge @"SECONDARY_AGE"
#define BXTagRecipeSecondaryTemperature @"SECONDARY_TEMP"
#define BXTagRecipeTertiaryAge @"TERTIARY_AGE"
#define BXTagRecipeTertiaryTemperature @"TERIARY_TEMP"
#define BXTagRecipeAge @"AGE"
#define BXTagRecipeAgeTemperature @"AGE_TEMP"
#define BXTagRecipeDate @"DATE"
#define BXTagRecipeCarbonation @"CARBONATION"
#define BXTagRecipeForcedCarbonation @"FORCED_CARBONATION"
#define BXTagRecipePrimingSugarName @"PRIMING_SUGAR_NAME"
#define BXTagRecipeCarbonationTemperature @"CARBONATION_TEMP"
#define BXTagRecipePrimingSugarEquivalent @"PRIMING_SUGAR_EQUIV"
#define BXTagRecipeKegPrimingFactor @"KEG_PRIMING_FACTOR"

// STYLE
#define BXTagStyleName @"NAME"
#define BXTagStyleCategory @"CATEGORY"
#define BXTagStyleVersion @"VERSION"
#define BXTagStyleCategoryNumber @"CATEGORY_NUMBER"
#define BXTagStyleLetter @"STYLE_LETTER"
#define BXTagStyleGuide @"STYLE_GUIDE"
#define BXTagStyleType @"TYPE"
#define BXTagStyleOGMin @"OG_MIN"
#define BXTagStyleOGMax @"OG_MAX"
#define BXTagStyleFGMin @"FG_MIN"
#define BXTagStyleFGMax @"FG_MAX"
#define BXTagStyleIBUMin @"IBU_MIN"
#define BXTagStyleIBUMax @"IBU_MAX"
#define BXTagStyleColorMin @"COLOR_MIN"
#define BXTagStyleColorMax @"COLOR_MAX"
#define BXTagStyleCarbMin @"CARB_MIN"
#define BXTagStyleCarbMax @"CARB_MAX"
#define BXTagStyleABVMin @"ABV_MIN"
#define BXTagStyleABVMax @"ABV_MAX"
#define BXTagStyleNotes @"NOTES"
#define BXTagStyleProfile @"PROFILE"
#define BXTagStyleIngredients @"INGREDIENTS"
#define BXTagStyleExamples @"EXAMPLES"

// HOP
#define BXTagHopName @"NAME"
#define BXTagHopVersion @"VERSION"
#define BXTagHopAlpha @"ALPHA"
#define BXTagHopAmount @"AMOUNT"
#define BXTagHopUse @"USE"
#define BXTagHopTime @"TIME"
#define BXTagHopNotes @"NOTES"
#define BXTagHopType @"TYPE"
#define BXTagHopForm @"FORM"
#define BXTagHopBeta @"BETA"
#define BXTagHopHSI @"HSI"
#define BXTagHopOrigin @"ORIGIN"
#define BXTagHopSubstitutes @"SUBSTITUTES"
#define BXTagHopHumulene @"HUMULENE"
#define BXTagHopCaryophyllene @"CARYOPHYLLENE"
#define BXTagHopCohumulone @"COHUMULONE"
#define BXTagHopMyrcene @"MYRCENE"

#endif
