#ifndef BeerXml_XmlTags_h
#define BeerXml_XmlTags_h

// MAIN TAGS
#define BXTagRecipes @"RECIPES"
#define BXTagRecipe @"RECIPE"
#define BXTagHops @"HOPS"
#define BXTagHop @"HOP"
#define BXTagStyle @"STYLE"
#define BXTagFermentables @"FERMENTABLES"
#define BXTagFermentable @"FERMENTABLE"
#define BXTagEquipments @"EQUIPMENTS"
#define BXTagEquipment @"EQUIPMENT"
#define BXTagMiscs @"MISCS"
#define BXTagMisc @"MISC"
#define BXTagWaters @"WATERS"
#define BXTagWater @"WATER"
#define BXTagYeasts @"YEASTS"
#define BXTagYeast @"YEAST"

// RECIPE
#define BXTagRecipeVersion @"VERSION"
#define BXTagRecipeName @"NAME"
#define BXTagRecipeType @"TYPE"
#define BXTagRecipeBrewer @"BREWER"
#define BXTagRecipeAssistantBrewer @"ASST_BREWER"
#define BXTagRecipeBatchSize @"BATCH_SIZE"
#define BXTagRecipeBoilSize @"BOIL_SIZE"
#define BXTagRecipeBoilTime @"BOIL_TIME"
#define BXTagRecipeEfficiency @"EFFICIENCY"
#define BXTagRecipeFermentables @"FERMENTABLES"
#define BXTagRecipeMiscs @"MISCS"
#define BXTagRecipeYeasts @"YEASTS"
#define BXTagRecipeWaters @"WATERS"
#define BXTagRecipeMash @"MASH"
#define BXTagRecipeNotes @"NOTES"
#define BXTagRecipeTasteNotes @"TASTE_NOTES"
#define BXTagRecipeTasteRating @"TASTE_RATING"
#define BXTagRecipeOriginalGravity @"OG"
#define BXTagRecipeFinalGravity @"FG"
#define BXTagRecipeFermentationStages @"FERMENTATION_STAGES"
#define BXTagRecipePrimaryAge @"PRIMARY_AGE"
#define BXTagRecipePrimaryTemperature @"PRIMARY_TEMP"
#define BXTagRecipeSecondaryAge @"SECONDARY_AGE"
#define BXTagRecipeSecondaryTemperature @"SECONDARY_TEMP"
#define BXTagRecipeTertiaryAge @"TERTIARY_AGE"
#define BXTagRecipeTertiaryTemperature @"TERIARY_TEMP"
#define BXTagRecipeAge @"AGE"
#define BXTagRecipeAgeTemperature @"AGE_TEMP"
#define BXTagRecipeDate @"DATE"
#define BXTagRecipeCarbonation @"CARBONATION"
#define BXTagRecipeForcedCarbonation @"FORCED_CARBONATION"
#define BXTagRecipePrimingSugarName @"PRIMING_SUGAR_NAME"
#define BXTagRecipeCarbonationTemperature @"CARBONATION_TEMP"
#define BXTagRecipePrimingSugarEquivalent @"PRIMING_SUGAR_EQUIV"
#define BXTagRecipeKegPrimingFactor @"KEG_PRIMING_FACTOR"

// STYLE
#define BXTagStyleName @"NAME"
#define BXTagStyleCategory @"CATEGORY"
#define BXTagStyleVersion @"VERSION"
#define BXTagStyleCategoryNumber @"CATEGORY_NUMBER"
#define BXTagStyleLetter @"STYLE_LETTER"
#define BXTagStyleGuide @"STYLE_GUIDE"
#define BXTagStyleType @"TYPE"
#define BXTagStyleOGMin @"OG_MIN"
#define BXTagStyleOGMax @"OG_MAX"
#define BXTagStyleFGMin @"FG_MIN"
#define BXTagStyleFGMax @"FG_MAX"
#define BXTagStyleIBUMin @"IBU_MIN"
#define BXTagStyleIBUMax @"IBU_MAX"
#define BXTagStyleColorMin @"COLOR_MIN"
#define BXTagStyleColorMax @"COLOR_MAX"
#define BXTagStyleCarbMin @"CARB_MIN"
#define BXTagStyleCarbMax @"CARB_MAX"
#define BXTagStyleABVMin @"ABV_MIN"
#define BXTagStyleABVMax @"ABV_MAX"
#define BXTagStyleNotes @"NOTES"
#define BXTagStyleProfile @"PROFILE"
#define BXTagStyleIngredients @"INGREDIENTS"
#define BXTagStyleExamples @"EXAMPLES"

// FERMENTABLES
#define BXTagFermentableName @"NAME"
#define BXTagFermentableVersion @"VERSION"
#define BXTagFermentableType @"TYPE"
#define BXTagFermentableAmount @"AMOUNT"
#define BXTagFermentableYield @"YIELD"
#define BXTagFermentableColor @"COLOR"
#define BXTagFermentableAddAfterBoil @"ADD_AFTER_BOIL"
#define BXTagFermentableOrigin @"ORIGIN"
#define BXTagFermentableSupplier @"SUPPLIER"
#define BXTagFermentableNotes @"NOTES"
#define BXTagFermentableCoarseFineDiff @"COARSE_FINE_DIFF"
#define BXTagFermentableMoisture @"MOISTURE"
#define BXTagFermentableDiastaticPower @"DIASTATIC_POWER"
#define BXTagFermentableProtein @"PROTEIN"
#define BXTagFermentableMaxInBatch @"MAX_IN_BATCH"
#define BXTagFermentableRecommendMash @"RECOMMEND_MASH"
#define BXTagFermentableIBUGalPerLB @"IBU_GAL_PER_LB"

// EQUIPMENT
#define BXTagEquipmentName @"NAME"
#define BXTagEquipmentVersion @"VERSION"
#define BXTagEquipmentBoilSize @"BOIL_SIZE"
#define BXTagEquipmentBatchSize @"BATCH_SIZE"
#define BXTagEquipmentTunVolume @"TUN_VOLUME"
#define BXTagEquipmentTunWeight @"TUN_WEIGHT"
#define BXTagEquipmentTunSpecificHeat @"TUN_SPECIFIC_HEAT"
#define BXTagEquipmentTopUpWater @"TOP_UP_WATER"
#define BXTagEquipmentTrubChillerLoss @"TRUB_CHILLER_LOSS"
#define BXTagEquipmentEvapRate @"EVAP_RATE"
#define BXTagEquipmentBoilTime @"BOIL_TIME"
#define BXTagEquipmentCalcBoilVolume @"CALC_BOIL_VOLUME"
#define BXTagEquipmentLauterDeadspace @"LAUTER_DEADSPACE"
#define BXTagEquipmentTopUpKettle @"TOP_UP_KETTLE"
#define BXTagEquipmentHopUtilization @"HOP_UTILIZATION"
#define BXTagEquipmentNotes @"NOTES"

// HOP
#define BXTagHopName @"NAME"
#define BXTagHopVersion @"VERSION"
#define BXTagHopAlpha @"ALPHA"
#define BXTagHopAmount @"AMOUNT"
#define BXTagHopUse @"USE"
#define BXTagHopTime @"TIME"
#define BXTagHopNotes @"NOTES"
#define BXTagHopType @"TYPE"
#define BXTagHopForm @"FORM"
#define BXTagHopBeta @"BETA"
#define BXTagHopHSI @"HSI"
#define BXTagHopOrigin @"ORIGIN"
#define BXTagHopSubstitutes @"SUBSTITUTES"
#define BXTagHopHumulene @"HUMULENE"
#define BXTagHopCaryophyllene @"CARYOPHYLLENE"
#define BXTagHopCohumulone @"COHUMULONE"
#define BXTagHopMyrcene @"MYRCENE"

// MISC
#define BXTagMiscName @"NAME"
#define BXTagMiscVersion @"VERSION"
#define BXTagMiscType @"TYPE"
#define BXTagMiscUse @"USE"
#define BXTagMiscTime @"TIME"
#define BXTagMiscAmount @"AMOUNT"
#define BXTagMiscAmountIsWeight @"AMOUNT_IS_WEIGHT"
#define BXTagMiscUseFor @"USE_FOR"
#define BXTagMiscNotes @"NOTES"

// WATER
#define BXTagWaterName @"NAME"
#define BXTagWaterVersion @"VERSION"
#define BXTagWaterAmount @"AMOUNT"
#define BXTagWaterCalcium @"CALCIUM"
#define BXTagWaterBicarbonate @"BICARBONATE"
#define BXTagWaterSulfate @"SULFATE"
#define BXTagWaterChloride @"CHLORIDE"
#define BXTagWaterSodium @"SODIUM"
#define BXTagWaterMagnesium @"MAGNESIUM"
#define BXTagWaterPh @"PH"
#define BXTagWaterNotes @"NOTES"

// YEAST
#define BXTagYeastName @"NAME"
#define BXTagYeastVersion @"VERSION"
#define BXTagYeastType @"TYPE"
#define BXTagYeastForm @"FORM"
#define BXTagYeastAmount @"AMOUNT"
#define BXTagYeastAmountIsWeight @"AMOUNT_IS_WEIGHT"
#define BXTagYeastLaboratory @"LABORATORY"
#define BXTagYeastProductId @"PRODUCT_ID"
#define BXTagYeastMinTemperature @"MIN_TEMPERATURE"
#define BXTagYeastMaxTemperature @"MAX_TEMPERATURE"
#define BXTagYeastFlocculation @"FLOCCULATION"
#define BXTagYeastAttenuation @"ATTENUATION"
#define BXTagYeastNotes @"NOTES"
#define BXTagYeastBestFor @"BEST_FOR"
#define BXTagYeastTimeCultured @"TIME_CULTURED"
#define BXTagYeastMaxReuse @"MAX_REUSE"
#define BXTagYeastAddToSecondary @"ADD_TO_SECONDARY"

#endif
